theme = "lynx"
title = "wty"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "wty"
  headline = "2025"
  image = "author.jpg"
  links = [
    { github = "https://github.com/wty2019wty/" },
    { link = { href = "https://space.bilibili.com/383861089", text = "BiliBili", icon = "bilibili" } },
    { link = { href = "https://um.9981000.xyz/", text = "um-react", icon = "um-react" } },
#   { link = { href = "http://rui9981.top/", text = "rui9981.top"} },
  ]

[markup.highlight]
  noClasses = true

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
