theme = "lynx"
title = "wty"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "wty"
  headline = "2025"
  image = "author.jpg"
  links = [
    { link = { href = "https://486520.xyz/", text = "AwaSubaru"} },
    { link = { href = "https://um-react.netlify.app/", text = "um", icon = "um-react" } },   
#    { link = { href = "https://s.486520.xyz", text = "status",icon = "uptime-kuma"}},
    { link = { href = "https://space.bilibili.com/383861089", text = "BiliBili", icon = "bilibili" } },
    { link = { href = "https://drawio.486520.xyz/", text = "Drawio"} },
    { github = "https://github.com/wty2019wty/" },

  ]





[markup.highlight]
  noClasses = true

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
