name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    # 这里指定ubuntu为最新版本, 使用指定版本也可, 比如 ubuntu-22.04
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # 运行hugo version可以查看本地hugo版本
          # 这里使用最新版本的hugo, 也可写具体的版本号, 与本地hugo版本保持一致, 比如 0.138.0
          hugo-version: latest
          # 查看hugo version的结果，如果本地是extended版本，就设置成true，反之设置成false
          extended: true

      - name: Build
        run: hugo  # 命令可以修改，比如草稿文章也想发表可改成hugo -D

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          # HUGO_TOKEN就是上面Actions Secret取的名字，要与自己取的名字保持一致
          personal_token: ${{ secrets.HUGO_TOKEN }}
          # <username>替换成自己的用户名
          external_repository: wty2019wty/wty2019wty.github.io
          # 现在默认分支都用main，比如用的是master分支，则改为master
          publish_branch: main
          publish_dir: ./public
	  destination: public

          # 可选配置, 每次博客更新后, 本仓库会自动往<username>.github.io仓库提交一次更新后的网站内容
          # 添加该项配置后, <username>.github.io仓库的提交信息就会使用本仓库的提交信息
          commit_message: ${{ github.event.head_commit.message }}
          cname: https://huxinme.top  # 填写自己的自定义域名, 如果没有自定义域名, 删除该项配置